name:                 saudetracker
version:              0.1.0.0
visibility:           public
id:                   saudetracker-0.1.0.0-inplace
key:                  saudetracker-0.1.0.0-inplace
license:              MIT
maintainer:           gabrielsilvacorrea2003@hotmail.com
author:               Gabriel Correa
homepage:             https://github.com/GabC-dev/saudetracker
synopsis:             Sistema de acompanhamento de saúde pessoal
category:             Web
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /Users/gabriel_correa/saudetracker/dist-newstyle/build/aarch64-osx/ghc-9.6.7/saudetracker-0.1.0.0/build

library-dirs:
    /Users/gabriel_correa/saudetracker/dist-newstyle/build/aarch64-osx/ghc-9.6.7/saudetracker-0.1.0.0/build

library-dirs-static:
    /Users/gabriel_correa/saudetracker/dist-newstyle/build/aarch64-osx/ghc-9.6.7/saudetracker-0.1.0.0/build

dynamic-library-dirs:
    /Users/gabriel_correa/saudetracker/dist-newstyle/build/aarch64-osx/ghc-9.6.7/saudetracker-0.1.0.0/build

data-dir:             /Users/gabriel_correa/saudetracker/.
hs-libraries:         HSsaudetracker-0.1.0.0-inplace
depends:
    sn-2.2.5.0-e779dd30 base-4.18.3.0 bytestring-0.11.5.4 mtl-2.3.1
    pstgrsql-smpl-0.7.0.1-96420005 srvnt-0.20.3.0-2488c9c2
    srvnt-srvr-0.20.3.0-58af04db text-2.0.2 time-1.12.2
    w-3.2.4-7029d87e w-crs-0.2.7-e2b5bc8e wrp-3.4.13-6be8db86

haddock-interfaces:
    /Users/gabriel_correa/saudetracker/dist-newstyle/build/aarch64-osx/ghc-9.6.7/saudetracker-0.1.0.0/doc/html/saudetracker/saudetracker.haddock

haddock-html:
    /Users/gabriel_correa/saudetracker/dist-newstyle/build/aarch64-osx/ghc-9.6.7/saudetracker-0.1.0.0/doc/html/saudetracker
